import Image from 'next/image';

export const metadata = {
  title: 'Главная | АН Арбат',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <main className="">
      <section className="">
        <div className="container"></div>
      </section>
    </main>
  );
}
